/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router
// 注：本仓未安装 @tanstack/router-plugin/cli，故手工维护——新增/删除 route 文件后在此同步。

import { Route as rootRoute } from './routes/__root'
import { Route as WebIDEImport } from './routes/webide'
import { Route as JobsImport } from './routes/jobs'
import { Route as NodesImport } from './routes/nodes'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'

const WebIDERoute = WebIDEImport.update({
  id: '/webide',
  path: '/webide',
  getParentRoute: () => rootRoute,
} as any)

const JobsRoute = JobsImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRoute,
} as any)

const NodesRoute = NodesImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/nodes': {
      id: '/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof NodesImport
      parentRoute: typeof rootRoute
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsImport
      parentRoute: typeof rootRoute
    }
    '/webide': {
      id: '/webide'
      path: '/webide'
      fullPath: '/webide'
      preLoaderRoute: typeof WebIDEImport
      parentRoute: typeof rootRoute
    }
  }
}

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LoginRoute,
  NodesRoute,
  JobsRoute,
  WebIDERoute,
])
