/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router
// 注：本仓未安装 @tanstack/router-plugin/cli，故手工维护——新增/删除 route 文件后在此同步。

import { Route as rootRoute } from './routes/__root'
import { Route as SchedulerImport } from './routes/scheduler'
import { Route as RbacImport } from './routes/rbac'
import { Route as MonitorImport } from './routes/monitor'
import { Route as BillingImport } from './routes/billing'
import { Route as AdminImport } from './routes/admin'
import { Route as WebIDEImport } from './routes/webide'
import { Route as HistoryImport } from './routes/history'
import { Route as JobsImport } from './routes/jobs'
import { Route as NodesImport } from './routes/nodes'
import { Route as LoginImport } from './routes/login'
import { Route as SettingsImport } from './routes/settings'
import { Route as LoginOidcCallbackImport } from './routes/login.oidc.callback'
import { Route as IndexImport } from './routes/index'

const SchedulerRoute = SchedulerImport.update({ id: '/scheduler', path: '/scheduler', getParentRoute: () => rootRoute } as any)
const RbacRoute = RbacImport.update({ id: '/rbac', path: '/rbac', getParentRoute: () => rootRoute } as any)
const MonitorRoute = MonitorImport.update({ id: '/monitor', path: '/monitor', getParentRoute: () => rootRoute } as any)
const BillingRoute = BillingImport.update({ id: '/billing', path: '/billing', getParentRoute: () => rootRoute } as any)
const AdminRoute = AdminImport.update({ id: '/admin', path: '/admin', getParentRoute: () => rootRoute } as any)
const HistoryRoute = HistoryImport.update({ id: '/history', path: '/history', getParentRoute: () => rootRoute } as any)
const WebIDERoute = WebIDEImport.update({ id: '/webide', path: '/webide', getParentRoute: () => rootRoute } as any)
const JobsRoute = JobsImport.update({ id: '/jobs', path: '/jobs', getParentRoute: () => rootRoute } as any)
const NodesRoute = NodesImport.update({ id: '/nodes', path: '/nodes', getParentRoute: () => rootRoute } as any)
const LoginRoute = LoginImport.update({ id: '/login', path: '/login', getParentRoute: () => rootRoute } as any)
const LoginOidcCallbackRoute = LoginOidcCallbackImport.update({ id: '/login/oidc/callback', path: '/login/oidc/callback', getParentRoute: () => rootRoute } as any)
const SettingsRoute = SettingsImport.update({ id: '/settings', path: '/settings', getParentRoute: () => rootRoute } as any)
const IndexRoute = IndexImport.update({ id: '/', path: '/', getParentRoute: () => rootRoute } as any)

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexImport; parentRoute: typeof rootRoute }
    '/login': { id: '/login'; path: '/login'; fullPath: '/login'; preLoaderRoute: typeof LoginImport; parentRoute: typeof rootRoute }
    '/login/oidc/callback': { id: '/login/oidc/callback'; path: '/login/oidc/callback'; fullPath: '/login/oidc/callback'; preLoaderRoute: typeof LoginOidcCallbackImport; parentRoute: typeof rootRoute }
    '/settings': { id: '/settings'; path: '/settings'; fullPath: '/settings'; preLoaderRoute: typeof SettingsImport; parentRoute: typeof rootRoute }
    '/nodes': { id: '/nodes'; path: '/nodes'; fullPath: '/nodes'; preLoaderRoute: typeof NodesImport; parentRoute: typeof rootRoute }
    '/jobs': { id: '/jobs'; path: '/jobs'; fullPath: '/jobs'; preLoaderRoute: typeof JobsImport; parentRoute: typeof rootRoute }
    '/webide': { id: '/webide'; path: '/webide'; fullPath: '/webide'; preLoaderRoute: typeof WebIDEImport; parentRoute: typeof rootRoute }
    '/history': { id: '/history'; path: '/history'; fullPath: '/history'; preLoaderRoute: typeof HistoryImport; parentRoute: typeof rootRoute }
    '/monitor': { id: '/monitor'; path: '/monitor'; fullPath: '/monitor'; preLoaderRoute: typeof MonitorImport; parentRoute: typeof rootRoute }
    '/billing': { id: '/billing'; path: '/billing'; fullPath: '/billing'; preLoaderRoute: typeof BillingImport; parentRoute: typeof rootRoute }
    '/admin': { id: '/admin'; path: '/admin'; fullPath: '/admin'; preLoaderRoute: typeof AdminImport; parentRoute: typeof rootRoute }
    '/rbac': { id: '/rbac'; path: '/rbac'; fullPath: '/rbac'; preLoaderRoute: typeof RbacImport; parentRoute: typeof rootRoute }
    '/scheduler': { id: '/scheduler'; path: '/scheduler'; fullPath: '/scheduler'; preLoaderRoute: typeof SchedulerImport; parentRoute: typeof rootRoute }
  }
}

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LoginRoute,
  LoginOidcCallbackRoute,
  SettingsRoute,
  NodesRoute,
  JobsRoute,
  WebIDERoute,
  HistoryRoute,
  MonitorRoute,
  BillingRoute,
  AdminRoute,
  RbacRoute,
  SchedulerRoute,
])
